language: node_js
node_js:
  - "4.3.2"
before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install build-essential -y
  - sudo apt-get install gcc-4.8 g++-4.8 -y
  - sudo apt-get install postgresql-client-9.4 libpq-dev -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++
  - export CC=gcc
  - gcc --version
notifications:
  slack: reekoh:eFsOWQBeXXs9jKVcqiqo4Ifg