apiVersion: 1.0.0
kind: Plugin
metadata:
  name: PostgreSQL Storage
  description: PostgreSQL storage plugin for Reekoh IoT Platform.
  icon: asset/icon/reekoh200x200.png
  signupLink: https://myservice.com/signup # ??
  type: Storage
  price: 0
  tags:
    - storage
    - postgre
    - postgresql
    
  release:
    version: 1.0.0
    notes: path/to/RELEASENOTESv1.0.0.md # ??
    documentation: README.md
    config:
      host:
        label: Host
        type: String
        maxLength: 1000
        required: true
        help: "Host of the PostgreSQL Database Server."
      port:
        label: Port
        type: Number
        required: true
        min: 1
        max: 65353
        help: "Port of the PostgreSQL Database Server."
      database:
        label: Databse
        type: String
        maxLength: 1000
        required: true
        help: "Database Name where to send the data to."
      table:
        label: Table
        type: String
        maxLength: 1000
        required: true
        help: "Table Name where data will be written into."
      user:
        label: User
        type: String
        maxLength: 1000
        required: true
        help: "(Optional) Username for PostgreSQL Server Authentication."
      password:
        label: Password
        type: Password
        maxLength: 1000
        required: true
        help: "(Optional) Password for PostgreSQL Server Authentication."
      fieldMapping:
        label: Field Mapping
        type: JSON
        maxLength: 10000
        required: true
        help: "List of the Table Fields/Columns. Input for this field is in JSON format {\"(field_name)\" : {\"source_field\" : \"value\", \"data_type\": \"value\", \"format\": \"value\"}}. field_name will be the name of the column in the PostgreSQL Table, source_field (required) value will be the name of the field in the JSON Data passed to the plugin, data_type (optional) there are 5 available data types that will convert data to it's proper type before saving we have String, Integer, Float, Boolean and DateTime, format is only available for DateTime data_type allowing users to specify the format of the device date/time data value. Kindly refer to the MomentJS docs for more details (http://momentjs.com/docs/#/parsing/string-format/)."
